// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuncnthcxlbbggzoixwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1bmNudGhjeGxiYmdnem9peHdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzMzkwNDMsImV4cCI6MjA3NTkxNTA0M30.y5grNSVAbB43CF_YOMni0m1_l2fstcujzMlWlsfjKhM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});